### ISSUE TITLE
feature search type

### ISSUE THREAD

**Issue by slmagus** [ChrisTerBeke/ThingiBrowser#11]
Thingiverse offers different search sorting(well sort of see below).  It would seem necessary for this extension to be able to display all models in a set requires the user be able to select which search type to perform i.e relevant, popular, text, # of makes, newest.

This could be accomplished by setting `?sort=popular ` or some other value in the requested URL.

An example I noticed is try to search for a very popular model the "Hairy Lion" by _primoz_ using the default sort method of "relevant" does not return the model. However, if you search using popular as the sorting you get the model. 

https://www.thingiverse.com/thing:2007221

I let Thingiverse know of this issue but no idea if they will fix it or not.

**Comment by ChrisTerBeke** [comment]
I've looked at the current API documentation and tried a few things, and it seems that it's currently not possible to influence the sorting order using the REST API. Let's see what they have to say regarding your ticket.

**Comment by ChrisTerBeke** [comment]
In the meantime I'm thinking about expanding the options in the top bar with buttons for global popular, featured and newest things:

![image](https://user-images.githubusercontent.com/1134120/64927500-cdc52500-d80b-11e9-8ac4-5620b93f8abb.png)

**Comment by slmagus** [comment]
I think this would be a great feature. 

> 
> 
> In the meantime I'm thinking about expanding the options in the top bar with buttons for global popular, featured and newest things:
> 
> ![image](https://user-images.githubusercontent.com/1134120/64927500-cdc52500-d80b-11e9-8ac4-5620b93f8abb.png)

I think this would be a great feature!

**Comment by ChrisTerBeke** [comment]
Coming to a Marketplace near you soon!

> I think this would be a great feature.
> 
> > In the meantime I'm thinking about expanding the options in the top bar with buttons for global popular, featured and newest things:
> > ![image](https://user-images.githubusercontent.com/1134120/64927500-cdc52500-d80b-11e9-8ac4-5620b93f8abb.png)

**Comment by ChrisTerBeke** [comment]
Closing this as there's no response from Thingiverse about the required API changes that are needed to complete this feature.
