### ISSUE TITLE
Packaged .qmlc and __pycache__ files

### ISSUE THREAD

**Issue by Ghostkeeper** [ChrisTerBeke/ThingiBrowser#12]
This plug-in comes with pre-packaged QMLC files. These files are not usable, since the QMLC file is a mmap of the memory used by the QML items. This is different between operating systems and Qt versions.

It also comes with a `__pycache__` folder for cached Python compiled classes. However this cache is made with Python 3.6 rather than Python 3.5 that Cura is shipped with.

Maybe it's better to remove these cached files from the distribution?

**Comment by ChrisTerBeke** [comment]
It seems this might be a bug with the packaging service of the Marketplace, that one is supposed to skip all files that contain amongst others `__pycache__` and `qmlc` in their paths. I'll have a look at that after the weekend. Of course it's still better to also not upload them at all.

**Comment by ChrisTerBeke** [comment]
I have check the last version of this plugin uploaded via the portal and there are no `__pycache__` and `qmlc` files in the .curapackage. They are filtered out of the source files when building the package. Please let me know if you have a different experience.
