### ISSUE TITLE
Add a MyMiniFactory Driver?

### ISSUE THREAD

**Issue by BohunkG4mer** [ChrisTerBeke/ThingiBrowser#15]
I was thinking that we could extract the current ThingiBrowser code into a driver and then add a MyMiniFactory driver to be able to bring in files from that site as well. What are you thoughts on adding that here vs just creating a new plugin for Cura? They both have Users with Things that can be Likes, in Collections, or Makes so the structure is similar enough that I think we could just go the route of a source selection and a driver that determines the view selection options.

**Comment by ChrisTerBeke** [comment]
Great idea! I think having both (and more later) repositories in the same plugin makes sense. We can change some of the styling/logos to make it less Thingiverse specific.

**Comment by BohunkG4mer** [comment]
FYI, I am currently working on this and it should be ready for first draft review fairly soon.

**Comment by ChrisTerBeke** [comment]
Nearly finished implementation in https://github.com/ChrisTerBeke/ThingiBrowser/pull/19.
