### ISSUE TITLE
Starting plugin, crashes Cura

### ISSUE THREAD

**Issue by ddt3** [ChrisTerBeke/ThingiBrowser#16]
Starting today, every time I open the thingiverse plugin, it crashes Cura. I have been using Cura 4.5 and this plugin for a few weeks without issue.. Could this be related to the Thingiverse site looking a bit different?

Curious if others see this behavior too.

**Comment by ChrisTerBeke** [comment]
Can you share the Cura crash logs? Without them I can't see what's going on.

**Comment by ChrisTerBeke** [comment]
It seems something in the Thingiverse API changed about 5 hours ago, I'm investigating.

**Comment by ChrisTerBeke** [comment]
It seems the Thingiverse API is broken. It is either not responding or returning `null`. Not something I can fix, so closing this issue. Hopefully Thingiverse will fix it soon.

**Comment by Ghostkeeper** [comment]
They renewed their entire site recently. Maybe the endpoints have moved?

See also https://sentry.io/organizations/ultimaker-o7/issues/1571939963/?project=1821564

**Comment by ChrisTerBeke** [comment]
Their API docs stayed the same. But the search endpoint seems completely broken (also when searching on their own site).

**Comment by ddt3** [comment]
Thanks for fixing this, this plugin makes life so much easier

**Comment by ChrisTerBeke** [comment]
Yeah the 1.5.1 release (now on the Marketplace) should at least fix the crashes. There's also a 2.0.0 version upcoming with a very big overhaul, adding MyMiniFactory as 2nd provider next to Thingiverse.
