### ISSUE TITLE
Thingiverse Driver Not Authenticating

### ISSUE THREAD

**Issue by BohunkG4mer** [ChrisTerBeke/ThingiBrowser#47]
It would seem that the Thingiverse driver is returning with a 502 Server Login Exception error when attempting to get My Likes/Makes/Collections/Things

2020-05-15 18:31:39,936 - WARNING - [MainThread] UM.Logger.warning [128]: API returned with status 502 and body []

**Comment by ChrisTerBeke** [comment]
Yup. It seems Thingiverse has introduced yet another breaking API change. None of these endpoints work anymore where they were fine a couple of days ago...

Also it seems impossible to get into contact with them and their documentation is horribly outdated. Thinking about dropping Thingiverse from the plugin as it's a giant PITA to maintain.

**Comment by ChrisTerBeke** [comment]
Likely fixed by https://github.com/ChrisTerBeke/ThingiBrowser/pull/50.
