### ISSUE TITLE
Cura crashes with empty data-set

### ISSUE THREAD

**Issue by ltsmith** [ChrisTerBeke/ThingiBrowser#5]
Found a bug that seems to occur when thingiverse returns an empty dataset.

**Steps to recreate:**
1. Open Thingiverse extension
2. Select search field, press enter key
3. Cura crashes due to JSON error: 
`\ThingiverseService.py", line 155, in _onSearchFinished
    self._things.extend(things)
TypeError: 'JSONObject' object is not iterable`

**Cura Version**: 4.1.0
**ThingiBrowser Version**: 1.1.1
**Platform**: Windows 10 10.0.17763
**Qt version**: 5.10.0

**Comment by ChrisTerBeke** [comment]
This was fixed in version 1.1.2 of the plugin. Thanks for reporting!
