### ISSUE TITLE
Get Thingiverse application approved

### ISSUE THREAD

**Issue by ChrisTerBeke** [ChrisTerBeke/ThingiBrowser#51]
Needed to scale OAuth2 flow beyond 10 users.

**Comment by ChrisTerBeke** [comment]
Application details filled out and submitted, waiting for approval.

**Comment by BohunkG4mer** [comment]
Have you gotten any sort of response from Thingiverse yet?

**Comment by ChrisTerBeke** [comment]
Nope. I've tried their official support form, Twitter and even Reddit to get into contact, but nothing. Their whole service is crappy. Also there appears to be another breaking change in the API again that I'll investigate later this week. Maybe we should drop support for them completely?

**Comment by BohunkG4mer** [comment]
Honestly it's looking like that may be the way to go. I am probably going to migrate my own things from there to MyMiniFactory too. Even their android app has been broken for too long...

**Comment by ChrisTerBeke** [comment]
Unlikely that this will ever happen. A PR is made to remove Thingiverse from the new sign-in flow and keep the old legacy flow working for it (until we completely remove Thingiverse support in the future maybe). Closing for now so we can prep the next release (hopefully together with the next Cura beta).
