### ISSUE TITLE
User Passwort 

### ISSUE THREAD

**Issue by j3sk0** [ChrisTerBeke/ThingiBrowser#57]
Hi, how can i get my password in to the Thingiverse acc to see my likes in thingiverse?

**Comment by ChrisTerBeke** [comment]
Hi. The current version in the Ultimaker Marketplace does not support user sign-in with username/password. We are working on an update to add this functionality (via the OAuth2 flow, so more secure than direct username/password in the plugin). Unfortunately we are blocked from releasing this by Thingiverse's app approval process (which is slow).
