### ISSUE TITLE
no .curapackage file 

### ISSUE THREAD

**Issue by Montezuma-69** [ChrisTerBeke/ThingiBrowser#65]
> Alternatively you can download the .curapackage file from one of the GitHub releases and drag this into Cura.
This information seems to be wrong, because no .curapackage file exists on git.

**Comment by BohunkG4mer** [comment]
Hello @Montezuma-69, they all exist here on the releases page (which is separate from the source code)
https://github.com/ChrisTerBeke/ThingiBrowser/releases

**Comment by Montezuma-69** [comment]
Thank you for this. There is no link from your Github Page to the releases page. So, nobody could find it.
