### ISSUE TITLE
Feature: support for other file types than STL

### ISSUE THREAD

**Issue by slmagus** [ChrisTerBeke/ThingiBrowser#9]
I don't have any import button to download the models. I see a details button which works, and link with the Thingiverse id

 I am using cura 4.2.1 and v1.1.4 of the plugin

**Comment by ChrisTerBeke** [comment]
Hi,

On the details page there should be a list of associated files, each with a download button. But this list is filtered to only show STL files, maybe the model you're looking at has no such files? Can you share a screenshot of the page?

**Comment by slmagus** [comment]
stl vs obj filtering is exactly the issue. As a bunch of other models "add to build plate work just fine. Is there a reason you filter out 'obj' files? I am far from an expert but from a functionality standpoint the plugin should be able to support any file type that thingiverse will let you download that can be imported into cura. Is that a possibility? If not maybe I can add a little warning that says hey this file needs to be manually downloaded.

![image](https://user-images.githubusercontent.com/1553090/62835490-375b7d80-bc27-11e9-9f6d-0a1e38d60a47.png)


![image](https://user-images.githubusercontent.com/1553090/62835483-2448ad80-bc27-11e9-97ff-8e1814b18ebe.png)

A known stl based model:

![image](https://user-images.githubusercontent.com/1553090/62835512-5ce88700-bc27-11e9-91ff-d6c5970db65f.png)

**Comment by slmagus** [comment]
Is this line the filter?

https://github.com/ChrisTerBeke/ThingiBrowser/blob/1f87d0943c85c6af11d9adf428e6e565981dca47/views/ThingFilesList.qml#L18

I could try hacking away at this but I need a little help with building the plugin into a .curapackage.

**Comment by ChrisTerBeke** [comment]
Thanks for testing that. I'll try and see if I can release a new version of the plugin with support for other file types that Cura supports.

**Comment by ChrisTerBeke** [comment]
PR #10 adds support for other file types (all that Cura can import). I'll submit a new package on the marketplace and wait for it to be reviewed.
